version: '3.8'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8040"
    restart: always
    labels:
      - "com.aioapp.description=Online to AIO service"
      - "com.aioapp.vendor=AIOApp Inc."