name: CI/CD Pipeline

on:
  push:
    branches:
      - fastapi
  pull_request:
    branches:
      - fastapi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build project
        run: echo "Build Successful!"
